//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumMafiaRestOnly.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVoteCountRest")]
    public interface IVoteCountRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoteCountRest/GetCurrentVoteCountModPost", ReplyAction="http://tempuri.org/IVoteCountRest/GetCurrentVoteCountModPostResponse")]
        string GetCurrentVoteCountModPost(string url, int postNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoteCountRest/GetCurrentVoteCountModPost", ReplyAction="http://tempuri.org/IVoteCountRest/GetCurrentVoteCountModPostResponse")]
        System.Threading.Tasks.Task<string> GetCurrentVoteCountModPostAsync(string url, int postNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoteCountRest/Ping", ReplyAction="http://tempuri.org/IVoteCountRest/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoteCountRest/Ping", ReplyAction="http://tempuri.org/IVoteCountRest/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoteCountRestChannel : ForumMafiaRestOnly.ServiceReference1.IVoteCountRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoteCountRestClient : System.ServiceModel.ClientBase<ForumMafiaRestOnly.ServiceReference1.IVoteCountRest>, ForumMafiaRestOnly.ServiceReference1.IVoteCountRest {
        
        public VoteCountRestClient() {
        }
        
        public VoteCountRestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoteCountRestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoteCountRestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoteCountRestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCurrentVoteCountModPost(string url, int postNumber) {
            return base.Channel.GetCurrentVoteCountModPost(url, postNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrentVoteCountModPostAsync(string url, int postNumber) {
            return base.Channel.GetCurrentVoteCountModPostAsync(url, postNumber);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
